Count,Message,Traceback,Nodes
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))","  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 319, in run
    self.execute_next_task()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 344, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 457, in execute_task
    task(self.user)
  File ""/home/ubuntu/SENG533-TeaStore-Evaluation/TeaStore/locust/locustfile.py"", line 24, in userExecuteTasks
    self.browse()
  File ""/home/ubuntu/SENG533-TeaStore-Evaluation/TeaStore/locust/locustfile.py"", line 81, in browse
    if product_request.ok:
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/models.py"", line 712, in ok
    self.raise_for_status()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 22, in raise_for_status
    raise self.error
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 173, in request
    response.raise_for_status()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 22, in raise_for_status
    raise self.error
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 202, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py"", line 501, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))","  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 319, in run
    self.execute_next_task()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 344, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 457, in execute_task
    task(self.user)
  File ""/home/ubuntu/SENG533-TeaStore-Evaluation/TeaStore/locust/locustfile.py"", line 24, in userExecuteTasks
    self.browse()
  File ""/home/ubuntu/SENG533-TeaStore-Evaluation/TeaStore/locust/locustfile.py"", line 84, in browse
    if cart_request.ok:
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/models.py"", line 712, in ok
    self.raise_for_status()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 22, in raise_for_status
    raise self.error
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 173, in request
    response.raise_for_status()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 22, in raise_for_status
    raise self.error
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 202, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 667, in send
    history = [resp for resp in gen]
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 667, in <listcomp>
    history = [resp for resp in gen]
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 245, in resolve_redirects
    **adapter_kwargs
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py"", line 501, in send
    raise ConnectionError(err, request=request)
",local
1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))","  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 319, in run
    self.execute_next_task()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 344, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/user/task.py"", line 457, in execute_task
    task(self.user)
  File ""/home/ubuntu/SENG533-TeaStore-Evaluation/TeaStore/locust/locustfile.py"", line 23, in userExecuteTasks
    self.login()
  File ""/home/ubuntu/SENG533-TeaStore-Evaluation/TeaStore/locust/locustfile.py"", line 59, in login
    if login_request.ok:
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/models.py"", line 712, in ok
    self.raise_for_status()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 22, in raise_for_status
    raise self.error
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 173, in request
    response.raise_for_status()
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 22, in raise_for_status
    raise self.error
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/locust/clients.py"", line 202, in _send_request_safe_mode
    return super().request(method, url, **kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/sessions.py"", line 645, in send
    r = adapter.send(request, **kwargs)
  File ""/home/ubuntu/.local/lib/python3.6/site-packages/requests/adapters.py"", line 501, in send
    raise ConnectionError(err, request=request)
",local
